'''Find whether the sum can be generated by the coins in the input
considering each coin for 1 time only.'''

'''ip:[2,3,5,6]
sum=11
op:"yes" '''

'''ip:[2,3,5,6]
sum=12
op:"no" '''

'''def fun():
    for i in range(n+1):
        l1=[0]*(n+1)
        l1[i][0]=1
    for i in range(1,len(l):
        for j in range(1,n+1):
            if l1[i-1]>j:
                l1[i][j]=11[i-1][j]
            else:
                if l1[i-1][j]==1:
                    l1[i][j]=11
                elif l1[i-1][j-lst[i-11]] == 1:
                    l1[i][j] = 1
                else:
                    l1[i][j] = 0
    print(l1[-1])
    if l1[-1]==1:
        print("Yes")
    else:
        print("No")
l=list(map(int,input().split(',')))
n=int(input())
fun()'''

def subset(nums, target_sum):
    n=len(nums)
    l=[[0]*(tar+1) for i in range(n+1)]    
    for i in range(n+1):
        l[i][0]=1    
    for i in range(1,n+1):
        for j in range(1,tar+1):
            if lst[i-1]>j:
                l[i][j]=l[i-1][j]
            else:
                if l[i-1][j]==1:
                    l[i][j]=1
                elif l[i-1][j-lst[i-1]] == 1:
                    l[i][j] = 1
                else:
                    l[i][j] = 0
    print(l[n][tar])
    if l[n][tar]==1:
        print("Yes")
    else:
        print("No")
lst=[2,3,5,6]
tar=11
subset(lst,tar)
